// This file is auto-generated by @hey-api/openapi-ts

export type JSONWebKey = {
    /**
     * The 'alg' (algorithm) parameter identifies the algorithm intended for use for the key.  The values used should either be registered in the IANA 'JSON Web Signature and Encryption Algorithms' registry established by [JWA] or be a value that contains a collision resistant name.
     */
    alg: string;
    crv?: string;
    d?: string;
    dp?: string;
    dq?: string;
    e?: string;
    k?: string;
    /**
     * The "kid" (key ID) parameter is used to match a specific key. This
     * is used, for example, to choose among a set of keys within a JWK Set
     * during key rollover. The format of the "kid" value is
     * unspecified.  When "kid" values are used within a JWK Set, different
     * keys within the JWK Set SHOULD use distinct "kid" values.  (One
     * example in which different keys might use the same "kid" value is if
     * they have different "kty" (key type) values but are considered to be
     * equivalent alternatives by the application using them.)  The "kid"
     * value is a case-sensitive string.
     */
    kid: string;
    /**
     * The "kty" (key type) parameter identifies the cryptographic
     * algorithm
     *
     * family used with the key, such as "RSA" or "EC". "kty" values should
     *
     * either be registered in the IANA "JSON Web Key Types" registry
     *
     * established by [JWA] or be a value that contains a Collision-
     *
     * Resistant Name.  The "kty" value is a case-sensitive string.
     */
    kty: string;
    n?: string;
    p?: string;
    q?: string;
    qi?: string;
    /**
     * Use ("public key use") identifies the intended use of
     * the public key. The "use" parameter is employed to indicate whether
     * a public key is used for encrypting data or verifying the signature
     * on data. Values are commonly "sig" (signature) or "enc" (encryption).
     */
    use: string;
    x?: string;
    /**
     * The "x5c" (X.509 certificate chain) parameter contains a chain of
     * one or more PKIX certificates [RFC5280].  The certificate chain is
     * represented as a JSON array of certificate value strings.  Each
     * string in the array is a base64-encoded (Section 4 of [RFC4648] --
     * not base64url-encoded) DER [ITU.X690.1994] PKIX certificate value.
     * The PKIX certificate containing the key value MUST be the first
     * certificate.
     */
    x5c?: Array<(string)>;
    y?: string;
};

export type JSONWebKeySet = {
    /**
     * The value of the 'keys' parameter is an array of JWK values.  By default, the order of the JWK values within the array does not imply an order of preference among them, although applications of JWK Sets can choose to assign a meaning to the order for their purposes, if desired.
     */
    keys?: Array<JSONWebKey>;
};

/**
 * It includes links to several endpoints (e.g. /oauth2/token) and exposes information on supported signature algorithms among others.
 */
export type WellKnown = {
    /**
     * URL of the OP's OAuth 2.0 Authorization Endpoint.
     */
    authorization_endpoint: string;
    /**
     * Boolean value specifying whether the OP supports use of the claims parameter, with true indicating support.
     */
    claims_parameter_supported?: boolean;
    /**
     * JSON array containing a list of the Claim Names of the Claims that the OpenID Provider MAY be able to supply values for. Note that for privacy or other reasons, this might not be an exhaustive list.
     */
    claims_supported?: Array<(string)>;
    /**
     * JSON array containing a list of the OAuth 2.0 Grant Type values that this OP supports.
     */
    grant_types_supported?: Array<(string)>;
    /**
     * JSON array containing a list of the JWS signing algorithms (alg values) supported by the OP for the ID Token to encode the Claims in a JWT.
     */
    id_token_signing_alg_values_supported: Array<(string)>;
    /**
     * URL using the https scheme with no query or fragment component that the OP asserts as its IssuerURL Identifier. If IssuerURL discovery is supported , this value MUST be identical to the issuer value returned by WebFinger. This also MUST be identical to the iss Claim value in ID Tokens issued from this IssuerURL.
     */
    issuer: string;
    /**
     * URL of the OP's JSON Web Key Set [JWK] document. This contains the signing key(s) the RP uses to validate signatures from the OP. The JWK Set MAY also contain the Server's encryption key(s), which are used by RPs to encrypt requests to the Server. When both signing and encryption keys are made available, a use (Key Use) parameter value is REQUIRED for all keys in the referenced JWK Set to indicate each key's intended usage. Although some algorithms allow the same key to be used for both signatures and encryption, doing so is NOT RECOMMENDED, as it is less secure. The JWK x5c parameter MAY be used to provide X.509 representations of keys provided. When used, the bare key values MUST still be present and MUST match those in the certificate.
     */
    jwks_uri: string;
    /**
     * Boolean value specifying whether the OP supports use of the request parameter, with true indicating support.
     */
    request_parameter_supported?: boolean;
    /**
     * Boolean value specifying whether the OP supports use of the request_uri parameter, with true indicating support.
     */
    request_uri_parameter_supported?: boolean;
    /**
     * Boolean value specifying whether the OP requires any request_uri values used to be pre-registered using the request_uris registration parameter.
     */
    require_request_uri_registration?: boolean;
    /**
     * JSON array containing a list of the OAuth 2.0 response_mode values that this OP supports.
     */
    response_modes_supported?: Array<(string)>;
    /**
     * JSON array containing a list of the OAuth 2.0 response_type values that this OP supports.
     */
    response_types_supported: Array<(string)>;
    /**
     * JSON array containing a list of the OAuth 2.0 [RFC6749] scope values that this server supports. The server MUST support the openid scope value. Servers MAY choose not to advertise some supported scope values even when this parameter is used.
     */
    scopes_supported?: Array<(string)>;
    /**
     * JSON array containing a list of the Subject Identifier types that this OP supports. Valid types include pairwise and public.
     */
    subject_types_supported: Array<(string)>;
    /**
     * URL of the OP's OAuth 2.0 Token Endpoint
     */
    token_endpoint: string;
    /**
     * JSON array containing a list of Client Authentication methods supported by this Token Endpoint. The options are client_secret_post, client_secret_basic, client_secret_jwt, and private_key_jwt, as described in Section 9 of OpenID Connect Core 1.0
     */
    token_endpoint_auth_methods_supported?: Array<(string)>;
};

/**
 * The token response
 */
export type OauthTokenResponse = {
    /**
     * The access token issued by the authorization server.
     */
    access_token?: string;
    /**
     * The lifetime in seconds of the access token.  For example, the value
     * "3600" denotes that the access token will
     * expire in one hour from the time the response was generated.
     */
    expires_in?: number;
    /**
     * The ID token is a JWT and signed using JWS.
     */
    id_token?: string;
    /**
     * The scope of the access token
     */
    scope?: string;
    /**
     * The type of the token issued
     */
    token_type?: string;
};

/**
 * Error responses are sent when an error (e.g. unauthorized, bad request, etc) occurred.
 */
export type ErrorResponse = {
    /**
     * Name is the error name.
     */
    error: string;
    /**
     * Code represents the error status code (404, 403, 401, ...).
     */
    error_code?: number;
    /**
     * Debug contains debug information. This is usually not available and has to be enabled.
     */
    error_debug?: string;
};

export type AuthenticationRequestPayload = {
    scope?: string;
    loginHint: string;
    bindingMessage?: string;
    /**
     * A positive integer representing the requested expiration time, in seconds, for the authentication.
     */
    requested_expiry?: unknown;
};

export type AuthenticationResponsePayload = {
    /**
     * Unique identifier for the authentication
     */
    auth_req_id: string;
    /**
     * A positive integer indicating the expiration time of the "auth_req_id" in seconds since the authentication request was received
     */
    expires_in: number;
    /**
     * A a positive integer indicating the minimum amount of time in seconds that the Client MUST wait between polling requests to the token endpoint.
     */
    interval: unknown;
};

export type UserExistsRequestPayload = {
    loginHint: string;
};

export type UserExistsResponsePayload = {
    exists: boolean;
};

/**
 * The name of the solution.
 * One word in lowercase letters is good.
 * See [HTTP headers](/docs/knowledge-base/http-headers).
 */
export type ParameterVipps_System_Name = string;

/**
 * The version number of the solution.
 * See [HTTP headers](/docs/knowledge-base/http-headers).
 */
export type ParameterVipps_System_Version = string;

/**
 * The name of the plugin (if applicable).
 * One word in lowercase letters is good.
 * See [HTTP headers](/docs/knowledge-base/http-headers).
 */
export type ParameterVipps_System_Plugin_Name = string;

/**
 * The version number of the ecommerce plugin (if applicable).
 * See [HTTP headers](/docs/knowledge-base/http-headers).
 */
export type ParameterVipps_System_Plugin_Version = string;

/**
 * This is a required parameter if you are a partner making API requests on behalf of a merchant.
 * The partner must use the merchant's MSN, not the partner's MSN.
 */
export type ParameterMerchant_Serial_Number = string;

export type DiscoverOpenIdConfigurationData = {
    /**
     * The name of the solution.
     * One word in lowercase letters is good.
     * See [HTTP headers](/docs/knowledge-base/http-headers).
     */
    vippsSystemName?: string;
    /**
     * The name of the plugin (if applicable).
     * One word in lowercase letters is good.
     * See [HTTP headers](/docs/knowledge-base/http-headers).
     */
    vippsSystemPluginName?: string;
    /**
     * The version number of the ecommerce plugin (if applicable).
     * See [HTTP headers](/docs/knowledge-base/http-headers).
     */
    vippsSystemPluginVersion?: string;
    /**
     * The version number of the solution.
     * See [HTTP headers](/docs/knowledge-base/http-headers).
     */
    vippsSystemVersion?: string;
};

export type DiscoverOpenIdConfigurationResponse = (WellKnown);

export type OauthAuthData = {
    /**
     * The name of the solution.
     * One word in lowercase letters is good.
     * See [HTTP headers](/docs/knowledge-base/http-headers).
     */
    vippsSystemName?: string;
    /**
     * The name of the plugin (if applicable).
     * One word in lowercase letters is good.
     * See [HTTP headers](/docs/knowledge-base/http-headers).
     */
    vippsSystemPluginName?: string;
    /**
     * The version number of the ecommerce plugin (if applicable).
     * See [HTTP headers](/docs/knowledge-base/http-headers).
     */
    vippsSystemPluginVersion?: string;
    /**
     * The version number of the solution.
     * See [HTTP headers](/docs/knowledge-base/http-headers).
     */
    vippsSystemVersion?: string;
};

export type Oauth2TokenData = {
    formData?: {
        /**
         * Value MUST be authorization_code.
         */
        grant_type: string;
        /**
         * The authorization code received from the authorization server as a query param on the redirect_uri.
         */
        code: string;
        /**
         * The redirect URL which the user agent is redirected to after finishing a login.
         * If the URL is using a custom URL scheme, such as myapp://, a path is required: myapp://path-to-something.
         * The URL must be exactly the same as the one specified on portal.vippsmobilepay.com.
         * Be extra careful with trailing slashes and URL-encoded entities.
         */
        redirect_uri: string;
        /**
         * The `client_id` is available on portal.vippsmobilepay.com, under the 'Developer' section.
         * This parameter is required if the token endpoint authentication method is set to `client_secret_post`.
         */
        client_id?: string;
        /**
         * The `client_secret` is available on portal.vippsmobilepay.com, under the 'Developer' section.
         * This parameter is required if the token endpoint authentication method is set to `client_secret_post`.
         */
        client_secret?: string;
        /**
         * Required if PKCE, https://tools.ietf.org/html/rfc7636, is used.
         */
        code_verifier?: string;
    };
    /**
     * This is a required parameter if you are a partner making API requests on behalf of a merchant.
     * The partner must use the merchant's MSN, not the partner's MSN.
     */
    merchantSerialNumber?: string;
    /**
     * The name of the solution.
     * One word in lowercase letters is good.
     * See [HTTP headers](/docs/knowledge-base/http-headers).
     */
    vippsSystemName?: string;
    /**
     * The name of the plugin (if applicable).
     * One word in lowercase letters is good.
     * See [HTTP headers](/docs/knowledge-base/http-headers).
     */
    vippsSystemPluginName?: string;
    /**
     * The version number of the ecommerce plugin (if applicable).
     * See [HTTP headers](/docs/knowledge-base/http-headers).
     */
    vippsSystemPluginVersion?: string;
    /**
     * The version number of the solution.
     * See [HTTP headers](/docs/knowledge-base/http-headers).
     */
    vippsSystemVersion?: string;
};

export type Oauth2TokenResponse = (OauthTokenResponse);

export type WellKnownData = {
    /**
     * The name of the solution.
     * One word in lowercase letters is good.
     * See [HTTP headers](/docs/knowledge-base/http-headers).
     */
    vippsSystemName?: string;
    /**
     * The name of the plugin (if applicable).
     * One word in lowercase letters is good.
     * See [HTTP headers](/docs/knowledge-base/http-headers).
     */
    vippsSystemPluginName?: string;
    /**
     * The version number of the ecommerce plugin (if applicable).
     * See [HTTP headers](/docs/knowledge-base/http-headers).
     */
    vippsSystemPluginVersion?: string;
    /**
     * The version number of the solution.
     * See [HTTP headers](/docs/knowledge-base/http-headers).
     */
    vippsSystemVersion?: string;
};

export type WellKnownResponse = (JSONWebKeySet);

export type PostVippsLoginCibaApiBackchannelAuthenticationData = {
    formData?: {
        authenticationRequestPayload?: AuthenticationRequestPayload;
    };
};

export type PostVippsLoginCibaApiBackchannelAuthenticationResponse = (AuthenticationResponsePayload);

export type UserExistsData = {
    formData?: {
        userExistsRequest?: UserExistsRequestPayload;
    };
};

export type UserExistsResponse = (UserExistsResponsePayload);

export type $OpenApiTs = {
    '/access-management-1.0/access/.well-known/openid-configuration': {
        get: {
            req: DiscoverOpenIdConfigurationData;
            res: {
                /**
                 * wellKnown
                 */
                200: WellKnown;
                /**
                 * genericError
                 */
                401: ErrorResponse;
                /**
                 * genericError
                 */
                500: ErrorResponse;
            };
        };
    };
    '/access-management-1.0/access/oauth2/auth': {
        get: {
            req: OauthAuthData;
            res: {
                /**
                 * Empty response
                 */
                302: unknown;
                /**
                 * genericError
                 */
                401: ErrorResponse;
                /**
                 * genericError
                 */
                500: ErrorResponse;
            };
        };
    };
    '/access-management-1.0/access/oauth2/token': {
        post: {
            req: Oauth2TokenData;
            res: {
                /**
                 * oauth2TokenResponse
                 */
                200: OauthTokenResponse;
                /**
                 * genericError
                 */
                401: ErrorResponse;
                /**
                 * genericError
                 */
                500: ErrorResponse;
            };
        };
    };
    '/access-management-1.0/access/.well-known/jwks.json': {
        get: {
            req: WellKnownData;
            res: {
                /**
                 * JSONWebKeySet
                 */
                200: JSONWebKeySet;
                /**
                 * genericError
                 */
                500: ErrorResponse;
            };
        };
    };
    '/vipps-login-ciba/api/backchannel/authentication': {
        post: {
            req: PostVippsLoginCibaApiBackchannelAuthenticationData;
            res: {
                /**
                 * OK
                 */
                200: AuthenticationResponsePayload;
            };
        };
    };
    '/vipps-login-ciba/api/v1/user-exists': {
        post: {
            req: UserExistsData;
            res: {
                /**
                 * OK
                 */
                200: UserExistsResponsePayload;
            };
        };
    };
};