name: Deno

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deno:
    runs-on: macos-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        run: brew install deno

      - name: Run tests
        run: deno fmt --check && deno lint && deno test --allow-net --parallel tests/

      - name: Check coverage
        run: deno test --coverage && deno run -A scripts/coverage.ts
